import React from 'react';
import {
  CheckCircle2,
  Cpu,
  Wrench,
  AlertTriangle,
  Layers,
  FileCheck,
  Brain,
  Ruler,
  Info,
} from 'lucide-react';
import type { AnalysisResult } from '../types';

interface AnalysisResultViewProps {
  result: AnalysisResult | null;
}

export const AnalysisResultView: React.FC<AnalysisResultViewProps> = ({ result }) => {
  if (!result) return null;

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-lg space-y-6">
      {/* 1. Header Bar: Operation & Calibrated Status */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-slate-800">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <FileCheck className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-100">Analysis Result</h2>
            <p className="text-[11px] text-slate-400 font-mono">Request ID: {result.request_id}</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Operation Pill */}
          <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-cyan-950/60 text-cyan-300 border border-cyan-800/60 font-mono">
            {result.operation.replace(/_/g, ' ')}
          </span>

          {/* Confidence Pill (Clearly distinguishing uncalibrated vs calibrated) */}
          <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-slate-800 text-slate-400 border border-slate-700 font-mono flex items-center gap-1.5">
            <Info className="w-3.5 h-3.5 text-amber-400" />
            <span>
              {result.confidence !== null && result.confidence !== undefined
                ? `Confidence: ${(result.confidence * 100).toFixed(0)}%`
                : 'Confidence: Qualitative (Uncalibrated)'}
            </span>
          </span>
        </div>
      </div>

      {/* 2. Primary Answer (Clearly demarcated as AI Interpretation) */}
      <div className="bg-slate-950/70 border border-slate-800 rounded-xl p-4.5 space-y-2">
        <div className="flex items-center justify-between">
          <span className="text-xs font-semibold text-emerald-400 flex items-center gap-1.5 uppercase tracking-wider">
            <Brain className="w-4 h-4" />
            <span>AI Interpretation</span>
          </span>
          <span className="text-[10px] text-slate-500 font-mono">
            Generated by Vision-Language Model
          </span>
        </div>
        <div className="text-sm text-slate-200 leading-relaxed whitespace-pre-line font-normal">
          {result.answer}
        </div>
      </div>

      {/* 3. Analysis Trace (User-Safe Execution Milestones - NO CHAIN OF THOUGHT) */}
      <div className="space-y-2">
        <h3 className="text-xs font-semibold text-slate-300 flex items-center gap-2 uppercase tracking-wider">
          <CheckCircle2 className="w-4 h-4 text-cyan-400" />
          <span>Analysis Trace / Execution Milestones</span>
        </h3>
        <div className="bg-slate-950/50 border border-slate-800/80 rounded-lg p-3">
          <ol className="space-y-2 text-xs">
            {result.analysis_trace.map((step, idx) => (
              <li key={idx} className="flex items-start gap-2.5 text-slate-300">
                <span className="w-4 h-4 rounded-full bg-cyan-950 border border-cyan-700/60 text-cyan-400 text-[10px] font-mono flex items-center justify-center shrink-0 mt-0.5">
                  {idx + 1}
                </span>
                <span className="font-mono text-slate-300">{step}</span>
              </li>
            ))}
          </ol>
        </div>
      </div>

      {/* 4. Measured & Derived Evidence (Clearly demarcated from AI Interpretation) */}
      <div className="space-y-2">
        <h3 className="text-xs font-semibold text-slate-300 flex items-center gap-2 uppercase tracking-wider">
          <Ruler className="w-4 h-4 text-emerald-400" />
          <span>Measured & Derived Evidence</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {result.evidence.map((ev) => (
            <div
              key={ev.evidence_id}
              className="bg-slate-950/40 border border-slate-800 rounded-lg p-3 space-y-2 text-xs"
            >
              <div className="flex items-center justify-between text-slate-400">
                <span className="font-mono text-[11px] text-emerald-400 font-medium">
                  {ev.evidence_id}
                </span>
                <span className="text-[10px] text-slate-500">{ev.source_asset}</span>
              </div>
              <p className="text-slate-300 font-medium">{ev.observation}</p>

              {ev.measurements && (
                <div className="pt-2 border-t border-slate-800/60 grid grid-cols-2 gap-x-2 gap-y-1 text-[11px] font-mono text-slate-400">
                  <div>Dimensions: {ev.measurements.width_px} × {ev.measurements.height_px} px</div>
                  <div>Channels: {ev.measurements.channels}</div>
                  <div>Format: {ev.measurements.is_geotiff ? 'GeoTIFF' : 'Standard Raster'}</div>
                  {ev.measurements.crs && <div>CRS: {ev.measurements.crs}</div>}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* 5. Tool & Model Provenance */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
        <div className="bg-slate-950/40 border border-slate-800 rounded-lg p-3">
          <div className="flex items-center gap-1.5 text-xs text-slate-400 mb-1.5 font-medium">
            <Wrench className="w-3.5 h-3.5 text-cyan-400" />
            <span>Tools Dispatched</span>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {result.tools_used.map((tool, i) => (
              <span
                key={i}
                className="px-2 py-0.5 rounded bg-slate-800 text-cyan-300 text-[11px] font-mono border border-slate-700"
              >
                {tool}
              </span>
            ))}
          </div>
        </div>

        <div className="bg-slate-950/40 border border-slate-800 rounded-lg p-3">
          <div className="flex items-center gap-1.5 text-xs text-slate-400 mb-1.5 font-medium">
            <Cpu className="w-3.5 h-3.5 text-emerald-400" />
            <span>Models & Adapters Used</span>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {result.models_used.map((model, i) => (
              <span
                key={i}
                className="px-2 py-0.5 rounded bg-slate-800 text-emerald-300 text-[11px] font-mono border border-slate-700"
              >
                {model}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* 6. Image Technical Metadata */}
      {result.metadata && (
        <div className="space-y-2">
          <h3 className="text-xs font-semibold text-slate-300 flex items-center gap-2 uppercase tracking-wider">
            <Layers className="w-4 h-4 text-purple-400" />
            <span>Image Metadata</span>
          </h3>
          <div className="bg-slate-950/40 border border-slate-800 rounded-lg p-3 overflow-x-auto">
            <table className="w-full text-xs font-mono text-left">
              <thead>
                <tr className="border-b border-slate-800 text-slate-500 text-[11px]">
                  <th className="pb-1.5 pr-4">Property</th>
                  <th className="pb-1.5">Value</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/40 text-slate-300">
                <tr>
                  <td className="py-1 text-slate-500">Filename</td>
                  <td className="py-1">{result.metadata.filename}</td>
                </tr>
                <tr>
                  <td className="py-1 text-slate-500">Raster Dimensions</td>
                  <td className="py-1">
                    {result.metadata.width} × {result.metadata.height} px ({result.metadata.channels} bands)
                  </td>
                </tr>
                <tr>
                  <td className="py-1 text-slate-500">Format</td>
                  <td className="py-1">{result.metadata.format}</td>
                </tr>
                <tr>
                  <td className="py-1 text-slate-500">GeoTIFF CRS</td>
                  <td className="py-1">
                    {result.metadata.crs ? (
                      <span className="text-emerald-400">{result.metadata.crs}</span>
                    ) : (
                      <span className="text-slate-500">None (Pixel Grid)</span>
                    )}
                  </td>
                </tr>
                {result.metadata.bounds && (
                  <tr>
                    <td className="py-1 text-slate-500">Bounding Box</td>
                    <td className="py-1 text-[11px]">
                      [{result.metadata.bounds.map((b: number) => b.toFixed(4)).join(', ')}]
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* 7. Operational & Scientific Warnings */}
      {result.warnings && result.warnings.length > 0 && (
        <div className="bg-amber-950/20 border border-amber-800/40 rounded-lg p-3 text-xs space-y-1">
          <div className="flex items-center gap-1.5 text-amber-400 font-semibold">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Scientific & Operational Advisory</span>
          </div>
          <ul className="list-disc list-inside text-amber-200/80 space-y-0.5 text-[11px]">
            {result.warnings.map((warn, i) => (
              <li key={i}>{warn}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};
